# Generated by Django 4.0.3 on 2022-05-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0003_comment'),
        ('bookMng', '0003_shoppingcart'),
    ]

    operations = [
    ]
